DELETE FROM SYS_USER;
ALTER TABLE SYS_USER ALTER COLUMN ID RESTART WITH 1;

DELETE FROM EMPLOYEE;
ALTER TABLE EMPLOYEE ALTER COLUMN ID RESTART WITH 1;

DELETE FROM PLANTING_RECORD;
ALTER TABLE PLANTING_RECORD ALTER COLUMN ID RESTART WITH 1;

DELETE FROM CLIMATE_RECORD;
ALTER TABLE CLIMATE_RECORD ALTER COLUMN ID RESTART WITH 1;

DELETE FROM PARCEL;
ALTER TABLE PARCEL ALTER COLUMN ID RESTART WITH 1;

DELETE FROM CROP;
ALTER TABLE CROP ALTER COLUMN ID RESTART WITH 1;