-- EMPLOYEE TABLE
INSERT INTO EMPLOYEE (NAME, SALARY) VALUES ('Jane Doe', 1000);
INSERT INTO EMPLOYEE (NAME, SALARY) VALUES ('John Doe', 1000);
INSERT INTO EMPLOYEE (NAME, SALARY) VALUES ('Willy Wonka', 1000);