-- EMPLOYEE TABLE
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Jane Doe', 1000, 2);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('John Doe', 1000, 2);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Willy Wonka', 1000, 2);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Hewet', 4170, 2);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Sibley', 1125, 2);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Randene', 8209, 2);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Nester', 8332, 2);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Lacie', 4128, 2);

INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Roselia', 2622, 3);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Hamnet', 8507, 3);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Lucille', 3651, 3);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Bryn', 2605, 3);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Rafael', 2730, 3);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Winthrop', 2607, 3);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Alberik', 5559, 3);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Dinny', 7013, 3);

INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Gaby', 4081, 4);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Salvidor', 4542, 4);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Bridie', 2436, 4);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Malchy', 4131, 4);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Dannie', 5709, 4);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Clarine', 8189, 4);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Ingeberg', 6805, 4);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Essy', 6051, 4);

INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Bone', 8183, 5);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Jane', 2755, 5);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Piggy', 6902, 5);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('King', 6745, 5);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Daveta', 2535, 5);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Tandie', 3698, 5);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Sheila', 1241, 5);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Hildagarde', 1625, 5);
INSERT INTO EMPLOYEE (NAME, SALARY, FK_USER) VALUES ('Gay', 3709, 5);