-- IRRIGATION_SYSTEM_USER TABLE
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, SUPERUSER) VALUES ('admin', 'admin', 1);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, SUPERUSER) VALUES ('jane', 'jane', 1);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, SUPERUSER) VALUES ('john', 'john', 0);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, SUPERUSER) VALUES ('anya', 'anya', 0);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, SUPERUSER) VALUES ('jimmy', 'jimmy', 0);