-- IRRIGATION_SYSTEM_USER TABLE
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, SUPERUSER) VALUES ('admin', 'admin', 1);
INSERT INTO IRRIGATION_SYSTEM_USER (USERNAME, PASSWORD, SUPERUSER) VALUES ('jane', 'jane', 0);